baseURL: 'http://lophi.dev/'
languageCode: 'en-ie'
title: 'LoPhi Developer'
theme: PaperMod

enableRobotsTXT: true

minify:
  minifyOutput: true

params:
  homeInfoParams:
      Title: "Jared Mullin"
      Content: "4th Year Computer Science and Information Technology Student at the National University of Ireland, Galway"
  socialIcons:
      - name: "github"
        url: "https://github.com/Jared-Mullin"
      - name: linkedin
        url: "https://linkedin.com/in/Jared-Mullin"

  env: production
  keywords: [Blog, Developer, Programming]
  author: Jared Mullin
  
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true

  label:
    text: "LoPhi"

  editPost:
      URL: "https://github.com/Jared-Mullin/Jared-Mullin.github.io/content"
      Text: "Suggest Changes" # edit text
      appendFilePath: true # to append file path to Edit link